style"tooltip"{
xthickness=4
ythickness=4
fg[NORMAL]=@fg_color
fg[PRELIGHT]=@fg_color
fg[SELECTED]=@fg_color
fg[ACTIVE]=@fg_color
fg[INSENSITIVE]=@fg_color
bg[NORMAL]=@bg_color
bg[PRELIGHT]=@bg_color
bg[SELECTED]=@bg_color
bg[ACTIVE]=@bg_color
bg[INSENSITIVE]=@bg_color
text[NORMAL]=@fg_color
text[PRELIGHT]=@fg_color
text[ACTIVE]=@fg_color
text[SELECTED]=@fg_color
text[INSENSITIVE]=@fg_color
engine"pixmap"{
image{
function=FLAT_BOX
file="images/check.png"
border={1,1,1,1}
stretch=TRUE}}}
widget"gtk-tooltip*"style"tooltip"
