#!/bin/sh

# key bindings
sxhkd &

# wallpaper
nitrogen --restore &

# set super key to launch rofi
ksuperkey -e 'Super_L=Alt_L|F1' &

# launch compton
al-compositor --start &
xfsettingsd &
xfce4-power-manager &
xscreensaver -no-splash &
#$HOME/.config/polybar/launch.sh
xrandr --output DisplayPort-0 --mode 3840x2160 --output HDMI-A-0 --auto --right-of DisplayPort-0E

# gnome polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


# panel
#al-tint2-session &
sleep 1; polybar -r bsp-bar &


bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width    3
bspc config window_gap      12
bspc config top_padding     18
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

bspc config split_ratio          0.54
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config pointer_modifier  mod1
bspc config click_to_focus    true
bspc config pointer_action1    move
bspc config pointer_action2   resize_side
bspc config pointer_action3   resize_corner

bspc rule -a thunar desktop='^1' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Galculator state=floating
bspc rule -a Void_Exit_Session state=floating layer=above
bspc rule -a Exit_Session state=floating layer=above
